name: build_test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_MAXSIZE: 500M
  CCACHE_KEY_SUFFIX: r22

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, compiler: clang-18 }
          - { os: ubuntu-24.04, compiler: gcc-14 }
          - { os: macos-13, compiler: clang-14 }
          - { os: macos-14, compiler: armv8-clang-14 }
          - { os: windows-2022, compiler: msvc-1940 }
    outputs:
      package_folder: ${{ steps.package_folder.outputs.package_folder }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ubuntu install ccache
        if: runner.os == 'Linux'
        run: |
          sudo apt install ccache
          ccache -V
      - name: macos install ccache
        if: runner.os == 'macOS'
        run: |
          brew install ccache
          ccache -V

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install conan

      - name: conan remote
        run: conan remote add odr https://artifactory.opendocument.app/artifactory/api/conan/conan
      - name: conan config
        run: conan config install .github/config/${{ matrix.os }}-${{ matrix.compiler }}/conan
      - name: conan install
        run: conan install . --version=0.0.0 --options "&:ODR_TEST=True" --build=never --output-folder=build

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ccache
            /Users/runner/Library/Caches/ccache
          key: ${{ matrix.os }}-${{ matrix.compiler }}-${{ env.CCACHE_KEY_SUFFIX }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.compiler }}-

      - name: conan create
        run: conan create . --version=0.0.0 --options "&:ODR_TEST=True" --test-folder test/downstream --format=json > created.json

      - run: python scripts/get_odrcore_package_folder.py created.json
        id: package_folder

      - name: Artifact package
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}-${{ matrix.compiler }}
          path: ${{ steps.package_folder.outputs.package_folder }}

      - name: Artifact dotconan2
        uses: actions/upload-artifact@v4
        with:
          name: dotconan2-${{ matrix.os }}-${{ matrix.compiler }}
          path: ~/.conan2
          if-no-files-found: error

  docker:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, compiler: clang-18 }
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/odr_core_cli
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha

      - uses: actions/download-artifact@v4
        with:
          name: dotconan2-${{ matrix.os }}-${{ matrix.compiler }}
          path: ~/.conan2

      - name: fix artifact permissions
        run: chmod +x ${{ needs.build.outputs.package_folder}/bin/*

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: cli
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/odr_core_cli:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/odr_core_cli:buildcache,mode=max

      # TODO try to run it

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, compiler: clang-18 }
          - { os: ubuntu-24.04, compiler: gcc-14 }
          - { os: macos-13, compiler: clang-14 }
          - { os: macos-14, compiler: armv8-clang-14 }
          - { os: windows-2022, compiler: msvc-1940 }
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_ANDIWAND }}
          submodules: true

      - name: ubuntu install tidy
        if: runner.os == 'Linux'
        run: sudo apt install tidy
      - name: macos install tidy
        if: runner.os == 'macOS'
        run: brew install tidy-html5

      - name: set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install -r test/scripts/requirements.txt

      - uses: actions/download-artifact@v4
        with:
          name: dotconan2-${{ matrix.os }}-${{ matrix.compiler }}
          path: ~/.conan2

      - run: ls -lh ${{ needs.build.outputs.package_folder}/bin/
      - name: fix artifact permissions
        run: chmod +x ${{ needs.build.outputs.package_folder}/bin/*

      - name: test
        if: runner.os != 'Windows'
        run: ./package/bin/odr_test
      - name: test
        if: runner.os == 'Windows'
        run: ./package/bin/odr_test.exe

      - name: tidy public test outputs
        run: python3 -u test/scripts/tidy_output.py output/odr-public/output
      - name: compare public test outputs
        run: |
          python3 -u test/scripts/compare_output.py \
            --driver firefox \
            --max-workers 1 \
            test/data/reference-output/odr-public/output \
            output/odr-public/output

      - name: tidy private test outputs
        run: python3 -u test/scripts/tidy_output.py output/odr-private/output
      - name: compare private test outputs
        run: |
          python3 -u test/scripts/compare_output.py \
            --driver firefox \
            --max-workers 1 \
            test/data/reference-output/odr-private/output \
            output/odr-private/output
