name: tidy

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, compiler: clang-18 }
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - run: clang-tidy --version

      - name: setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: install python dependencies
        run: pip install --upgrade pip conan

      - name: conan remote
        run: conan remote add odr https://artifactory.opendocument.app/artifactory/api/conan/conan
      - name: conan config
        run: conan config install .github/config/${{ matrix.os }}-${{ matrix.compiler }}/conan

      - name: conan install
        run: conan install . --options "&:ODR_CLANG_TIDY=True" --build=never --output-folder=build

      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ccache
            /Users/runner/Library/Caches/ccache
          key: ${{ matrix.os }}-${{ matrix.compiler }}-${{ env.CCACHE_KEY_SUFFIX }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.compiler }}-

      - name: conan create
        run: conan create . --options "&:ODR_CLANG_TIDY=True"
